version: 0.2

phases:
  install:
    commands:
        - cd $HOME
        - wget https://raw.github.com/technomancy/leiningen/stable/bin/lein; chmod +x lein; mv lein /bin;
        - LEIN_ROOT=true lein
  pre_build:
    commands:
  build:
    commands:
        - cd $CODEBUILD_SRC_DIR
        - LEIN_ROOT=true lein cljsbuild once dev
  post_build:
    commands:
artifacts:
  files:
    - target/*
    - resources/public/js/out/*
    - resources/*
    - application.py
    - requirements.txt
    - index.html
